dist: xenial

language: minimal
sudo: require
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
    packages:
      - qt512base qt512serialport qt512-meta-minimal
script:
  # - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt-get update
  - sudo apt-get install libgl-dev
  - sudo apt install python3 python3-pip
  - pip3 install --user jinja2
  # todo install only what is needed
  # - sudo apt install qt512base qt512serialport qt512-meta-minimal
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=Release ..
  - make -j$(nproc) || make fix-ui
  - make -j$(nproc)
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  # - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
  - echo $PATH
  - export PATH=/opt/qt512/bin:$PATH
  - cp ../open-esc-qt.desktop .
  - ./linuxdeployqt-continuous-x86_64.AppImage open-esc-qt -appimage -unsupported-allow-new-glibc -verbose=0
  - pwd
  - ls

before_deploy:
  - git tag continuous-deployment -f
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/jaxxzer/open-esc-qt
  - git push origin continuous-deployment -f

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file:
    - build/open-esc-qt*.AppImage
    - com-handle.cpp
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
