dist: xenial

language: minimal

script:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt-get update
  - sudo apt-get install libgl-dev
  - sudo apt install python3 python3-pip
  - pip3 install --user jinja2
  # todo install only what is needed
  - sudo apt install qt512-meta-full
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make fix-ui
  - make
