dist: xenial

language: minimal

script:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt-get update
  - sudo apt install qt512base qt512serialport
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make fix-ui
  - make
